name: Build binaries

on:
  push:
    branches:
    - main

jobs:
  binaries:
    name: Cross-platform binary builds
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: ">=1.18"

      - name: Create directory
        run: mkdir dist

      - name: Build linux/amd64
        run: CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o dist/freeswitch_exporter-linux-amd64

      - name: Build linux/arm64
        run: CGO_ENABLED=0 GOOS=linux GOARCH=arm64 go build -o dist/freeswitch_exporter-linux-arm64

      - name: Upload build artifacts
        uses: skx/github-action-publish-binaries@master
        env:
          GITHUB_TOKEN: ${{ secrets.MROJECT_TOKEN }}
        with:
          args: ./dist/*
